# Generated by Django 3.1 on 2020-08-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyname', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
